### ISSUE TITLE
Message: Only variable references should be returned by reference

### ISSUE THREAD

**Issue by abdulrojak288** [youngjunkim/codeigniter-facebook-google-login#6]
A PHP Error was encountered
Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257

Fatal error: Uncaught Error: Call to undefined function mysql_pconnect() in C:\xampp\htdocs\codeigniter-facebook-google-login-master\system\database\drivers\mysql\mysql_driver.php:91 Stack trace: #0 C:\xampp\htdocs\codeigniter-facebook-google-login-master\system\database\DB_driver.php(115): CI_DB_mysql_driver->db_pconnect() #1 C:\xampp\htdocs\codeigniter-facebook-google-login-master\system\database\DB.php(148): CI_DB_driver->initialize() #2 C:\xampp\htdocs\codeigniter-facebook-google-login-master\system\core\Loader.php(346): DB(Array, NULL) #3 C:\xampp\htdocs\codeigniter-facebook-google-login-master\system\core\Loader.php(1171): CI_Loader->database() #4 C:\xampp\htdocs\codeigniter-facebook-google-login-master\system\core\Loader.php(152): CI_Loader->_ci_autoloader() #5 C:\xampp\htdocs\codeigniter-facebook-google-login-master\system\core\Controller.php(51): CI_Loader->initialize() #6 C:\xampp\htdocs\codeigniter-facebook-google-login-master\application\controllers\auth.php(7): CI_Controller->__construct() #7 C:\xampp\htdocs\ in C:\xampp\htdocs\codeigniter-facebook-google-login-master\system\database\drivers\mysql\mysql_driver.php on line 91

**Comment by nikbird12** [comment]
Filename: core/Common.php

Line Number: 257

change 

`return $_config[0] =& $config; `

TO

```
$_config[0] =& $config;
return $_config[0]; 
```
